Feature/phase2
inplayer-org/inplayer-ios-sdk pull request #22
Opened 2019-03-20 15:01 UTC by odimitrov

Add 4 additional endpoints:
- exportUserData
- getRegisterFields
- getSubscriptions
- getPurchaseHistory

Updated documentation.

2019-03-26 12:28 UTC, srdjanRakic requested changes

2019-03-26 12:28 UTC, srdjanRakic commented on Source/Core/Account.swift
> +        public static func exportUserData(password: String,
Should be named `exportData`

2019-03-26 17:29 UTC, odimitrov commented on Source/Core/Account.swift
> +        public static func exportUserData(password: String,
Done.

2019-03-27 11:59 UTC, srdjanRakic approved these changes

2019-03-27 12:31 UTC, merged